choco install notepadplusplus -y
choco install Firefox -y
choco install GoogleChrome -y
choco install putty -y
choco install ccleaner -y
choco install 7zip -y
choco install flashplayerplugin -y
choco install adobereader -y
choco install flashplayeractivex -y
choco install AdobeAIR -y
choco install InkScape -y
choco install audacity -y
choco install audacity-lame -y
choco install vlc -y
choco install libreoffice -y
#choco install libreoffice-help -y
choco install jre8 -y
choco install adobeshockwaveplayer -y
choco install Silverlight -y
choco install gimp -y
